---
- name: Tower API
  hosts: localhost
  become: false
  vars_files: api.yml
  vars:
    tower_host: "10.100.12.150"
    tower_job: "Demo%20Job%20Template"

  tasks:
    - name: Launch job
      uri:
        url: "http://{{ tower_host }}/api/v2/job_templates/{{ tower_job }}/launch/"
        method: POST
        validate_certs: no
        return_content: yes
        user: "{{ tower_user }}"
        password: "{{ tower_pass }}"
        force_basic_auth: yes
        status_code: 201
